config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  get    '/book/new'        => 'books#new',     as: :new_book
  post   '/book'            => 'books#create',  as: :create_book
  get    '/book/edit/:id'   => 'books#edit',    as: :edit_book
  patch  '/book/:id'        => 'books#update',  as: :update_book
  get    '/book/:id'        => 'books#show',    as: :show_book
  get    '/book/delete/:id' => 'books#delete',  as: :delete_book
  delete '/book/:id'        => 'books#destroy', as: :destroy_book

end

app/models/book.rb
# frozen_string_literal: true

class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
# frozen_string_literal: true

require 'books/creator'
require 'books/destroyer'
require 'books/presenter'
require 'books/updater'

class BooksController < ApplicationController
  def index
    @books = Book.all.map { |book| Books::Presenter.new(book) }
  end

  def new
    @book = Book.new
  end

  def create
    creation = Books::Creator.execute(book_params)
    if creation.successful?
      announce(creation, 'created')
    else
      repeat(creation, :new)
    end
  end

  def edit
    @book = Book.find(book_id)
  end

  def update
    update = Books::Updater.execute(book_id, book_params)
    update.successful? ? announce(update, 'updated') : repeat(update, :edit)
  end

  def show
    @book = Books::Presenter.new(Book.find(book_id))
  end

  def delete
    @book = Books::Presenter.new(Book.find(book_id))
  end

  def destroy
    destruction = Books::Destroyer.execute(book_id)
    if destruction.successful?
      announce(destruction, 'deleted')
    else
      repeat(destruction, :index)
    end
  end

  private

  def book_params
    params.require(:book).permit(:id, :title, :filename)
  end

  def book_id
    params[:id]
  end

  def announce(result, action)
    notice = "Successfully #{action} book #{result.book.title}."
    redirect_to root_path, notice: notice
  end

  def repeat(result, template)
    @book = result.book
    flash.now[:alert] = result.messages
    render template
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/books/_book_info.html.erb
<h2><%= @book.title %></h2>
<p>File name: <%= @book.filename %></p>

app/views/books/delete.html.erb
<h2>Delete Book</h2>

<%= form_for(@book.instance, url: destroy_book_path, method: :delete) do |form| %>
  <p>Are you sure you want to delete this book?</p>
  <%= form.submit "Delete book", class: "button-alert" %>
  <%= link_to("Go back", root_path, class: "button-main form-link") %>
<% end %>

<%= render "book_info" %>

app/views/books/edit.html.erb
<h2>Edit Book</h2>

<%= form_for(@book, url: update_book_path) do |form| %>
  <p class="form-pair">
    <%= form.text_field(:title, class: "form-text", required: true) %>
    <%= form.label(:title, "Title (required)", class: "form-label") %>
  </p>

  <p class="form-pair">
    <%= form.text_field(:filename, class: "form-text") %>
    <%= form.label(:filename, class: "form-label") %>
  </p>

  <%= form.submit "Update book", class: "button-main" %>
<% end %>

app/views/books/index.html.erb
  <div class="main-navigation">
    <%= link_to "Add new book", new_book_path, class: "button-main-index" %>
  </div>

<% if @books.any? %>
  <ul class="main-list">
  <% @books.each do |book| %>
    <li>
      <div class="item-info">
        <h2><%= link_to(book.title, show_book_path(book.id)) %></h2>
      </div>
      <div class="item-buttons">
        <%= link_to("Edit Book", edit_book_path(book.id), class: "button-secondary") %>
        <%= link_to("Delete Book", delete_book_path(book.id), class: "button-alert") %>
      </div>
    </li>
  <% end %>
  </ul>
<% else %>
  <p>No books have been added yet.</p>
<% end %>

app/views/books/new.html.erb
<h2>Add new book</h2>

<%= form_for(@book, url: create_book_path) do |form| %>
  <p class="form-pair">
    <%= form.text_field(:title, class: "form-text", required: true) %>
    <%= form.label(:title, "Title (required)", class: "form-label") %>
  </p>

  <p class="form-pair">
    <%= form.text_field(:filename, class: "form-text") %>
    <%= form.label(:filename, class: "form-label") %>
  </p>

  <%= form.submit "Create book", class: "button-main" %>
<% end %>

app/views/books/show.html.erb
<%= render "book_info" %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Kitepkana</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- <link rel="apple-touch-icon" href="apple-touch-icon.png"> -->
        <!-- Place favicon.ico in the root directory -->

        <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,500i,800" rel="stylesheet">
        <%= stylesheet_link_tag 'application', media: 'all' %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

        <% if flash.any? %>
          <ul class="flashes">
            <% flash.alert.try(:each) do |alert| %>
              <li class="alert"><%= alert %></li>
            <% end %>

            <% if flash.notice %>
              <li class="notice"><%= flash.notice %></li>
            <% end %>
          </ul>
        <% end %>

        <div class="main-content">
          <h1><%= link_to "Kitepkana", root_path, class: "main-title" %></h1>
          <%= yield %>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.0.min.js" integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I=" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.0.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
        <script>
            window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
            ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
        </script>
        <script src="https://www.google-analytics.com/analytics.js" async defer></script>
    </body>
</html>